steps:
  #- label: "Print working directory of agent"
  #  command:
  #    - ls -al
  #    - pwd
  #- label: "Execute PowerShell script"
  #  command:
  #    - pwsh -Command Get-ChildItem
  #    - pwsh -File ./test.ps1
  #  plugins:
  #    - docker:
  #        image: mcr.microsoft.com/powershell:preview
  - label: "Get Git short rev"
    command: buildkite-agent meta-data set 'short-commit' `git rev-parse --short=7 ${BUILDKITE_COMMIT}`
  - wait
  - label: "Build and run"
    env:
      BUILDKITE_COMMIT_SHORT: `buildkite-agent meta-data get 'short-commit'`
    command:
      - dotnet build ./${BUILDKITE_PIPELINE_SLUG}.csproj
      - dotnet ./bin/Debug/netcoreapp2.1/${BUILDKITE_PIPELINE_SLUG}.dll
      - dotnet pack --include-symbols --include-source --version-suffix ${BUILDKITE_COMMIT_SHORT} -p:PackageVersion=1.0.${BUILDKITE_BUILD_NUMBER} ./${BUILDKITE_PIPELINE_SLUG}.csproj
      - dotnet nuget push ./bin/Debug/${BUILDKITE_PIPELINE_SLUG}.1.0.${BUILDKITE_BUILD_NUMBER}.nupkg --source Artifactory
    artifact_paths:
      - ./**/*.nupkg
    plugins:
      - docker:
          image: microsoft/dotnet:sdk