steps:
  #- label: "Print working directory of agent"
  #  command:
  #    - ls -al
  #    - pwd
  - label: "Execute PowerShell script"
    command:
      - pwsh -Command Get-ChildItem
      - pwsh -File ./test.ps1
    plugins:
      - docker:
          image: mcr.microsoft.com/powershell:preview
  - label: "Build and run"
    command:
      - dotnet build ./${BUILDKITE_PIPELINE_SLUG}.csproj
      - dotnet ./bin/Debug/netcoreapp2.1/${BUILDKITE_PIPELINE_SLUG}.dll
    plugins:
      - docker:
          image: microsoft/dotnet:sdk