steps:
  - label: "Print PowerShell Core Version"
    command:
      - pwd
    plugins:
      - docker#v2.1.0:
          image: mcr.microsoft.com/powershell:preview
          workdir: /var/workspace
          volumes:
            - "/buildkite/builds/${BUILDKITE_AGENT_NAME}/ttm:/var/workspace"
          shell: ['pwsh', '-Command']