steps:
  #- label: "Print working directory of agent"
  #  command:
  #    - ls -al
  #    - pwd
  #- label: "Execute PowerShell script"
  #  command:
  #    - pwsh -Command Get-ChildItem
  #    - pwsh -File ./test.ps1
  #  plugins:
  #    - docker:
  #        image: mcr.microsoft.com/powershell:preview
  - label: "Get Git short rev"
    command:
      - export BUILDKITE_COMMIT_SHORTREV=`git rev-parse --short=7 ${BUILDKITE_COMMIT}`
      #- git rev-parse --short=7 ${BUILDKITE_COMMIT}
      - buildkite-agent meta-data set buildkite:git:shortrev $${BUILDKITE_COMMIT_SHORTREV}
  - wait
  - label: "Build and run"
    env:
      BUILDKITE_COMMIT_SHORT: 
    command:
      - echo Git version is `git --version`
      - echo Git short rev is `buildkite-agent meta-data get buildkite:git:shortrev`
      - dotnet build ./${BUILDKITE_PIPELINE_SLUG}.csproj
      - dotnet ./bin/Debug/netcoreapp2.1/${BUILDKITE_PIPELINE_SLUG}.dll
      - dotnet pack --include-symbols --include-source -p:PackageVersion=1.0.${BUILDKITE_BUILD_NUMBER}-`buildkite-agent meta-data get buildkite:git:shortrev` ./${BUILDKITE_PIPELINE_SLUG}.csproj
      - dotnet nuget push ./bin/Debug/${BUILDKITE_PIPELINE_SLUG}.1.0.${BUILDKITE_BUILD_NUMBER}.nupkg --source https://artifactory.trimble.tools/artifactory/api/nuget/v3/trimbletransportation-connectedfleetcentral-nuget/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}/ --api-key kyle_estes@trimble.com:AKCp5cbn8WKFiy4vwGtVNaJY1QmgwtipzTTz7Numr444WbYNWsWRpqBTpawXhmm1uufUZEoQf --no-service-endpoint
    artifact_paths:
      - ./**/*.nupkg
    plugins:
      - docker:
          image: microsoft/dotnet:sdk