steps:
  - label: "Print working directory of agent"
    command:
      - ls -al
      - pwd
  - label: "Print PowerShell Core Version"
    command:
      - Get-ChildItem /var/workspace/${BUILDKITE_PIPELINE_SLUG}
    plugins:
      - docker#v2.1.0:
          image: mcr.microsoft.com/powershell:preview
          #workdir: /var/workspace
          volumes:
            - "/buildkite/builds/${BUILDKITE_AGENT_NAME}/ttm:/var/workspace"
          shell: ['pwsh', '-Command']