steps:
  - label: "Print working directory of agent"
    command:
      - ls -al
      - pwd
      - pwsh -File ./test.ps1
  - label: "Print PowerShell Core Version"
    command:
      - Get-ChildItem /var/workspace/${BUILDKITE_PIPELINE_SLUG}
    plugins:
      - docker:
          image: mcr.microsoft.com/powershell:preview
          #shell: ['pwsh', '-Command']